### ISSUE TITLE
Error when deploy to Heroku

### ISSUE THREAD

**Issue by t4ngth00** [andyet/signalmaster#102]
Hello there,

Does anyone try to deploy this server to Heroku? 
Can you guys give me a tutorial for it?
I built successfully but the server didn't work.

**Comment by lucaurso** [comment]
Did you manage to make it work on Heroku? If yes, how?

**Comment by lucaurso** [comment]
@t4ngth00 I managed to make it work. 
Check this answer on Stackoverflow https://stackoverflow.com/a/22809750

**Comment by t4ngth00** [comment]
I've tried to use it with express and it has worked fine. However, by using with express, I got problem to run "https" on localhost.

**Comment by t4ngth00** [comment]
Anyway, thank you so much.

**Comment by jeffin07** [comment]
Hello every on e when i try to run it shows error

D:\webrtc-signal-master>node server.js
dev environment detected
fs.js:642
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'D:\webrtc-signal-master\server.key'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.readFileSync (fs.js:510:33)
    at Object.<anonymous> (D:\webrtc-signal-master\server.js:16:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

D:\webrtc-signal-master>
can anyone help
