### ISSUE TITLE
Server crash when request arrive while using config/development.json

### ISSUE THREAD

**Issue by shamun** [andyet/signalmaster#113]
Crash when request has arrived to http://localhost:8888
```
# node server.js
&yet -- signal master is running at: http://localhost:8888
crypto.js:91
  this._handle.init(hmac, toBuf(key));
               ^

TypeError: Key must be a buffer
    at TypeError (native)
    at new Hmac (crypto.js:91:16)
    at Object.Hmac (crypto.js:89:12)
```

**Comment by shamun** [comment]
https://github.com/andyet/signalmaster/issues/114
