### ISSUE TITLE
Error: Cannot find module 'socket.io-client/dist/socket.io.min.js'

### ISSUE THREAD

**Issue by rafelamer** [andyet/signalmaster#138]
I'm trying to run signalmaster in a CentOS 7 machine. I'm doing the following to install it

git clone https://github.com/andyet/signalmaster.git
cd signalmaster
npm install

and then

node server.js

I get the error

module.js:478
    throw err;
    ^

Error: Cannot find module 'socket.io-client/dist/socket.io.min.js'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.resolve (internal/module.js:27:19)
    at Server.serveClient (/root/signalmaster/node_modules/socket.io/lib/index.js:101:33)
    at new Server (/root/signalmaster/node_modules/socket.io/lib/index.js:48:8)
    at Function.Server (/root/signalmaster/node_modules/socket.io/lib/index.js:40:41)
    at module.exports (/root/signalmaster/sockets.js:6:23)
    at Object.<anonymous> (/root/signalmaster/server.js:31:1)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)

**Comment by shawnmaten** [comment]
I know this is dated but for anyone else that comes across this issue, if you add the option `serveClient: false` to the socket.io listen call you can fix this error.

```js
// sockets.js
// var io = socketIO.listen(server);
var io = socketIO.listen(server, { serveClient: false });
```

https://github.com/simplewebrtc/signalmaster/blob/master/sockets.js#L6
