### ISSUE TITLE
How to use https?

### ISSUE THREAD

**Issue by eshengsky** [andyet/signalmaster#35]
I changed the filed 'secure' to 'true' in file dev_config.json, then I run the server with:
node server.js, but it shows the error as following:
dev environment detected
fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.<anonymous> (F:\simplewebrtc\server.js:17:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)

Is it because I didn't set fileds 'key' ,'cert'...? I don't know how to set.
Could someone help me?

**Comment by emredagli** [comment]
As I understand you needed to define certificate files:
https://help.ubuntu.com/12.04/serverguide/certificates-and-security.html
