### ISSUE TITLE
does socket.io is not the proper version?

### ISSUE THREAD

**Issue by jdzyzh** [andyet/signalmaster#61]
when I run the simplewebrtc-master client, the signal server prompt the followings:

Missing error handler on `socket`.
TypeError: Cannot read property 'resources' of undefined
    at D:\Program Files\nodejs\signalmaster-master\sockets.js:157:59
    at Array.forEach (native)
    at describeRoom (D:\Program Files\nodejs\signalmaster-master\sockets.js:156:
30)
    at Socket.join (D:\Program Files\nodejs\signalmaster-master\sockets.js:70:30
)
    at emitTwo (events.js:87:13)
    at Socket.emit (events.js:172:7)
    at Socket.onevent (D:\Program Files\nodejs\node_modules\socket.io\lib\socket
.js:335:8)
    at Socket.onpacket (D:\Program Files\nodejs\node_modules\socket.io\lib\socke
t.js:295:12)
    at Client.ondecoded (D:\Program Files\nodejs\node_modules\socket.io\lib\clie
nt.js:193:14)
    at Decoder.Emitter.emit (D:\Program Files\nodejs\node_modules\component-emit
ter\index.js:134:20)

**Comment by jdzyzh** [comment]
debug messages
console.log(clients);
console.log(Object.keys(clients));

Room { sockets: { '/#6jwJasFQ7_SUHb1NAAAA': true }, length: 1 }
[ 'sockets', 'length' ]

**Comment by dmr** [comment]
I think I have the same issue. Did you solve it yet @jdzyzh ?

**Comment by dmr** [comment]
npm install --> installed socket.io@1.4.4

**Comment by SpottedPaint** [comment]
I got similar error running socket.io@1.4.5 works with socket.io@1.3.7
I went down versions one by one it seems like latest version to work for me is 1.3.7
