### ISSUE TITLE
Error when connecting over webRTC

### ISSUE THREAD

**Issue by computurus** [andyet/signalmaster#74]
I have installed and configured the singalmaster server as my singaling server for webRTC using simpleWebRTC. Trying to connect two peers, the server encounters the following error: 

`TypeError: Cannot read property 'resources' of undefined
    at /home/topit/signalmaster-master/sockets.js:139:59
    at Array.forEach (native)
    at describeRoom (/home/topit/signalmaster-master/sockets.js:138:30)
    at Socket.join (/home/topit/signalmaster-master/sockets.js:66:30)
    at Socket.EventEmitter.emit (events.js:98:17)
    at Socket.onevent (/home/topit/signalmaster-master/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/home/topit/signalmaster-master/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/home/topit/signalmaster-master/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/home/topit/signalmaster-master/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/home/topit/signalmaster-master/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)
Missing error handler on `socket`.
TypeError: Cannot read property 'resources' of undefined
    at /home/topit/signalmaster-master/sockets.js:139:59
    at Array.forEach (native)
    at describeRoom (/home/topit/signalmaster-master/sockets.js:138:30)
    at Socket.join (/home/topit/signalmaster-master/sockets.js:66:30)
    at Socket.EventEmitter.emit (events.js:98:17)
    at Socket.onevent (/home/topit/signalmaster-master/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/home/topit/signalmaster-master/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/home/topit/signalmaster-master/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/home/topit/signalmaster-master/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/home/topit/signalmaster-master/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)
`

**Comment by bogacode** [comment]
exactly the same here.
To verify I did the simpliest demo from the website, using the sandbox server. Worked.
Just changed the url to a current clone of master where only a valid ssl certs was integrated. Signalmaster crashed with exactly the same error computurus got.
tried secure: true and "other things". But nothing helped.

**Comment by bogacode** [comment]
the socket version is not yet fixed in package.json from the master tree.
"socket.io": "^1.3.7" 
should be without "^"

https://github.com/andyet/signalmaster/pull/65

**Comment by fippo** [comment]
should be fixed with #65. Let me know if not.
